CREATE DATABASE HITAYA
GO

USE HITAYA
GO



CREATE TABLE EMPLOYEES
(
	[EMPID] VARCHAR(20) CONSTRAINT uniqz UNIQUE NOT NULL,
	[NAME] VARCHAR(20) NOT NULL,
	[EMAILID] VARCHAR(20)  CONSTRAINT pk_EmailId PRIMARY KEY,
	[DEPARTMENT] VARCHAR(20) NOT NULL,
	[ROLEID] VARCHAR(20) NOT NULL CONSTRAINT chk_Role CHECK ([ROLEID] IN ('JL1','JL2','JL3','JL4','JL5','JL6','JL7','JL8','JL9'))
)
GO


INSERT INTO EMPLOYEES(EMPID,NAME,EMAILID,DEPARTMENT,ROLEID) VALUES ('10800116107','Arnab Das','raj713335@gmail.com','STG','JL3')


CREATE PROCEDURE EMPLOYEE_DETAILS
(
	@EMPID VARCHAR(20),
	@NAME VARCHAR(20),
	@EMAILID VARCHAR(20),
	@DEPARTMENT VARCHAR(20),
	@ROLEID VARCHAR(20)
)
AS
BEGIN
	DECLARE @RES TINYINT
	BEGIN TRY
		INSERT INTO EMPLOYEES(EMPID,NAME,EMAILID,DEPARTMENT,ROLEID) 
		VALUES (@EMPID,@NAME,@EMAILID,@DEPARTMENT,@ROLEID)
		RETURN 1
	END TRY
	BEGIN CATCH
		RETURN -99
	END CATCH
END
GO



DECLARE @RETURNVAL INT
EXEC @RETURNVAL = EMPLOYEE_DETAILS '10800116108','Arnab Das','raj71333c5@gmail.com','STG','JL3'
SELECT @RETURNVAL AS RETURNVAL

SELECT * FROM EMPLOYEES

DROP TABLE USERDETAILS

CREATE TABLE USERDETAILS
(
	[USERID] INT IDENTITY(10000000,1),
	[EMPID] VARCHAR(20) NOT NULL,
	[NAME] VARCHAR(20) NOT NULL,
	[EMAILID] VARCHAR(20)  CONSTRAINT pk_EmailIdx PRIMARY KEY,
	[PASSWORD] VARCHAR(20) NOT NULL,
	[DEPARTMENT] VARCHAR(20) NOT NULL,
	[CRYPTO_ID] VARCHAR(200) NOT NULL,
	[LIMIT] DECIMAL(38,18) NOT NULL,
	[ROLEID] VARCHAR(20) NOT NULL CONSTRAINT chk_Rolex CHECK ([ROLEID] IN ('JL1','JL2','JL3','JL4','JL5','JL6','JL7','JL8','JL9')),
	[ID_CARD] VARBINARY(MAX) NOT NULL
)
GO 



INSERT INTO USERDETAILS(EMPID,NAME,EMAILID,PASSWORD,DEPARTMENT,CRYPTO_ID,LIMIT,ROLEID,ID_CARD) SELECT '10800116107','Arnab Das','raj713335@gmail.com','12345678','STG','0xdejjjjaasjw27yswshwsggs','200','JL3',BulkColumn FROM Openrowset(Bulk 'C:\Users\ZEUS\Desktop\Hitaya\Extras\0.png',Single_Blob) as image


IF OBJECT_ID('USP_INSERT_USER_DETAILS')  IS NOT NULL
DROP PROC USP_INSERT_USER_DETAILS
GO

CREATE PROCEDURE USP_INSERT_USER_DETAILS
(
	@EMAILID VARCHAR(20),
	@PASSWORD VARCHAR(20),
	@CRYPTO_ID VARCHAR(200),
	@LIMIT DECIMAL(38,18),
	@ID_CARD VARBINARY(MAX)

)
AS
BEGIN
	DECLARE @EMPID VARCHAR(20),@NAME VARCHAR(20),@DEPARTMENT VARCHAR(20),@ROLEID VARCHAR(20)
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM EMPLOYEES WHERE EMAILID=@EMAILID)
		RETURN -1
		SELECT @EMPID=EMPID,@NAME=NAME,@DEPARTMENT=DEPARTMENT,@ROLEID=ROLEID FROM EMPLOYEES WHERE @EMAILID=EMAILID
		INSERT INTO USERDETAILS(EMPID,NAME,EMAILID,PASSWORD,DEPARTMENT,CRYPTO_ID,LIMIT,ROLEID,ID_CARD) SELECT @EMPID,@NAME,@EMAILID,@PASSWORD,@DEPARTMENT,@CRYPTO_ID,@LIMIT,@ROLEID,OPENROWSET(BULK N''' + @ID_CARD + ''', SINGLE_BLOB) as [imageDedicated]
		RETURN 1
	END TRY
	BEGIN CATCH
		RETURN -99
	END CATCH
END
GO


DECLARE @RETURNVAL INT
EXEC @RETURNVAL = USP_INSERT_USER_DETAILS 'raj71333c5@gmail.com','12345678','0x77263289191FGSH1b','200.00', 'C:\Users\ZEUS\Desktop\Hitaya\Extras\0.png'
SELECT @RETURNVAL AS RETURNVAL


SELECT * FROM USERDETAILS

SELECT * FROM EMPLOYEES