CREATE DATABASE HITAYA
GO

USE HITAYA
GO


IF OBJECT_ID('USERDETAILS')  IS NOT NULL
DROP TABLE USERDETAILS
GO



IF OBJECT_ID('usp_RegisterUser')  IS NOT NULL
DROP PROC usp_RegisterUser
GO

CREATE TABLE EMPLOYEES
(
	[EMPID] VARCHAR(20) CONSTRAINT uniqz UNIQUE NOT NULL,
	[NAME] VARCHAR(20) NOT NULL,
	[EMAILID] VARCHAR(20)  CONSTRAINT pk_EmailId PRIMARY KEY,
	[DEPARTMENT] VARCHAR(20) NOT NULL,
	[ROLEID] VARCHAR(20) NOT NULL CONSTRAINT chk_Role CHECK ([ROLEID] IN ('JL1','JL2','JL3','JL4','JL5','JL6','JL7','JL8','JL9'))
)
GO


INSERT INTO EMPLOYEES(EMPID,NAME,EMAILID,DEPARTMENT,ROLEID) VALUES ('10800116107','Arnab Das','raj713335@gmail.com','STG','JL3')


CREATE PROCEDURE EMPLOYEE_DETAILS
(
	@EMPID VARCHAR(20),
	@NAME VARCHAR(20),
	@EMAILID VARCHAR(20),
	@DEPARTMENT VARCHAR(20),
	@ROLEID VARCHAR(20)
)
AS
BEGIN
	DECLARE @RES TINYINT
	BEGIN TRY
		INSERT INTO EMPLOYEES(EMPID,NAME,EMAILID,DEPARTMENT,ROLEID) 
		VALUES (@EMPID,@NAME,@EMAILID,@DEPARTMENT,@ROLEID)
		RETURN 1
	END TRY
	BEGIN CATCH
		RETURN -99
	END CATCH
END
GO



DECLARE @RETURNVAL INT
EXEC @RETURNVAL = EMPLOYEE_DETAILS '10800116108','Arnab Das','raj71333c5@gmail.com','STG','JL3'
SELECT @RETURNVAL AS RETURNVAL

SELECT * FROM EMPLOYEES


CREATE TABLE USERDETAILS
(
	[USERID] INT IDENTITY(10000000,1),
	[EMPID] VARCHAR(20) NOT NULL,
	[NAME] VARCHAR(20) NOT NULL,
	[EMAILID] VARCHAR(20)  CONSTRAINT pk_EmailId PRIMARY KEY,
	[PASSWORD] VARCHAR(20) NOT NULL,
	[DEPARTMENT] VARCHAR(20) NOT NULL,
	[CRYPTO_ID] VARCHAR(200) NOT NULL,
	[LIMIT] VARCHAR(200) NOT NULL,
	[ROLEID] VARCHAR(20) NOT NULL CONSTRAINT chk_Role CHECK ([ROLEID] IN ('JL1','JL2','JL3','JL4','JL5','JL6','JL7','JL8','JL9'))
)
GO 



INSERT INTO USERDETAILS(USERID,NAME,EMAILID,PASSWORD,DEPARTMENT,CRYPTO_ID,LIMIT,ROLEID) VALUES ('Arnab','Das','raj713335@gmail.com','12345678','Admin')