CREATE DATABASE HITAYA
GO

USE HITAYA
GO



CREATE TABLE Doctors
(
	[ID] INT IDENTITY(10000000,1) CONSTRAINT pk_EmailId PRIMARY KEY,
	[NAME] VARCHAR(20) NOT NULL,
	[SPECIALIZATION] VARCHAR(20)  NOT NULL,
	[EDUCATION] VARCHAR(20) NOT NULL,
	[EXPERIENCE] INT NOT NULL,
	[AVAILABILITY] VARCHAR(100) NOT NULL,
	[TIMINGS] VARCHAR(50) NOT NULL
)
GO

DROP TABLE Doctors


INSERT INTO Doctors(NAME,SPECIALIZATION,EDUCATION,EXPERIENCE,AVAILABILITY,TIMINGS) VALUES ('Vincent Strange','Orthopedic','MBBS, MD',10,'Mon, Tue, Wed, Fri, Sat','10am - 7pm')
INSERT INTO Doctors(NAME,SPECIALIZATION,EDUCATION,EXPERIENCE,AVAILABILITY,TIMINGS) VALUES ('Bruce Wayne','Cardiologist','MD, MS',17,'Sun, Tue, Wed, Sat','11am - 5pm')
INSERT INTO Doctors(NAME,SPECIALIZATION,EDUCATION,EXPERIENCE,AVAILABILITY,TIMINGS) VALUES ('Peter Parker','Gynaecologist','MBBS, MD, DM',15,'Sun, Mon, Thr, Fri, Sat','11am - 6pm')
INSERT INTO Doctors(NAME,SPECIALIZATION,EDUCATION,EXPERIENCE,AVAILABILITY,TIMINGS) VALUES ('Natassa Romanoff','Dermatologist','MBBS DMRD',18,'Tue, Wed, Sat','12pm - 8pm')
Go


SELECT * FROM Doctors

CREATE FUNCTION ufn_GetDoctorDetails()
RETURNS TABLE 
AS
	RETURN (SELECT * FROM Doctors)
GO


SELECT * FROM ufn_GetDoctorDetails()